### PR TITLE
added withStyleName methods to layout, row and column (resolves JarekToro/responsive-layout#30)

### PR DESCRIPTION
**Pull request by derBertW**
wasn't sure how to fit a belonging test for this into your project. Just give me a hint howto if you want me to do it. Also added a withStyleName method to layout. Just throw it away if you don't want this (there are no other of these convenience methods there).

### CODE REVIEW

**Comment by JarekToro** [comment]
You the man! After business hours I will review it and accept then put in directory. Really Appreciate the PR!

**Comment by JarekToro** [comment]
Thanks again! Its in latest release. Now on Vaadin Directory

**Comment by derBertW** [comment]
That was fast. Thank you for accepting the PR. Your addon is exactly the part I was missing in Vaadin to not longing for Bootstrap.

**Comment by JarekToro** [comment]
Thats awesome to hear!

**Pull request merged**
